// Generated by CoffeeScript 1.4.0
var HelloWorld,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

importScripts("/siebog/radigost.js");

HelloWorld = (function(_super) {

  __extends(HelloWorld, _super);

  function HelloWorld() {
    return HelloWorld.__super__.constructor.apply(this, arguments);
  }

  HelloWorld.prototype.onMessage = function(msg) {
    return this.onStep("Hello from " + this.aid.str + "!");
  };

  return HelloWorld;

})(Agent);

self.agentInstance = new HelloWorld;
