// Generated by CoffeeScript 1.4.0
var MobileAgent,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

importScripts("/siebog/radigost.js");

MobileAgent = (function(_super) {

  __extends(MobileAgent, _super);

  function MobileAgent() {
    return MobileAgent.__super__.constructor.apply(this, arguments);
  }

  MobileAgent.prototype.onInit = function(args) {
    return this.moveToServer();
  };

  return MobileAgent;

})(Agent);

self.agentInstance = new MobileAgent;
