// Generated by CoffeeScript 1.4.0
var Agent;

Agent = (function() {

  function Agent() {
    this.aid = null;
  }

  Agent.prototype.post = function(msg) {
    return self.postMessage(msg);
  };

  Agent.prototype.onInit = function(args) {
    var msg;
    msg = {
      opcode: OpCode.INIT,
      aid: this.aid
    };
    return this.post(msg);
  };

  Agent.prototype.onMessage = function(msg) {};

  Agent.prototype.onStep = function(step) {
    var msg;
    msg = {
      opcode: OpCode.STEP,
      aid: this.aid,
      info: step
    };
    return this.post(msg);
  };

  return Agent;

})();

self.__AGENT_INSTANCE__ = null;

self.onmessage = function(ev) {
  var msg;
  msg = ev.data;
  if (msg.opcode === OpCode.INIT) {
    self.__AGENT_INSTANCE__.aid = msg.aid;
    return self.__AGENT_INSTANCE__.onInit(msg.args);
  } else {
    return self.__AGENT_INSTANCE__.onMessage(msg);
  }
};
